<card-form
    :path="'{{ $confirm_url }}'"
    placeholder-card-number="{{ trans('general.form.enter', ['field' => trans('general.card.number')]) }}"
    placeholder-card-name="{{ trans('general.form.enter', ['field' => trans('general.card.name')]) }}"
    placeholder-card-cvv="{{ trans('general.form.enter', ['field' => trans('general.card.cvv')]) }}"
    text-card-number="{{ trans('general.card.number') }}"
    text-card-name="{{ trans('general.card.name') }}"
    text-expiration-date="{{ trans('general.card.expiration_date') }}"
    text-month="{{ trans('general.month') }}"
    text-year="{{ trans('general.year') }}"
    text-cvv="{{ trans('general.card.cvv') }}"
    textButton="{{ trans('general.confirm') }}"
    textCard="{{ trans_choice('general.card.cards', 2) }}"
    textNewCard="{{  trans('general.form.add_new', ['field' => trans_choice('general.card.cards', 1)]) }}"
    textStoreCard="{{ trans('general.card.save') }} "
    :store-card="{{ !empty($store_card) ? 'true' : 'false' }}"
    :cards="{{ !empty($cards) ? json_encode($cards) : json_encode([]) }}"
    :form-data="formData"
/>
