

<div class="card" style="padding: 0; padding-left: 15px; padding-right: 15px; border-radius: 0; box-shadow: 0 4px 16px rgba(0,0,0,.2);">
    <div class="card-body">
        @if ($documentTemplate)
            @switch($documentTemplate)
                @case('classic')
                    <x-documents.template.classic
                        type="{{ $type }}"
                        :document="$document"
                        document-template="{{ $documentTemplate }}"
                        logo="{{ $logo }}"
                        background-color="{{ $backgroundColor }}"
                        hide-footer="{{ $hideFooter }}"
                        hide-company-logo="{{ $hideCompanyLogo }}"
                        hide-company-details="{{ $hideCompanyDetails }}"
                        hide-company-name="{{ $hideCompanyName }}"
                        hide-company-address="{{ $hideCompanyAddress }}"
                        hide-company-tax-number="{{ $hideCompanyTaxNumber }}"
                        hide-company-phone="{{ $hideCompanyPhone }}"
                        hide-company-email="{{ $hideCompanyEmail }}"
                        hide-contact-info="{{ $hideContactInfo }}"
                        hide-contact-name="{{ $hideContactName }}"
                        hide-contact-address="{{ $hideContactAddress }}"
                        hide-contact-tax-number="{{ $hideContactTaxNumber }}"
                        hide-contact-phone="{{ $hideContactPhone }}"
                        hide-contact-email="{{ $hideContactEmail }}"
                        hide-order-number="{{ $hideOrderNumber }}"
                        hide-document-number="{{ $hideDocumentNumber }}"
                        hide-issued-at="{{ $hideIssuedAt }}"
                        hide-due-at="{{ $hideDueAt }}"
                        text-contact-info="{{ $textContactInfo }}"
                        text-issued-at="{{ $textIssuedAt }}"
                        text-document-number="{{ $textDocumentNumber }}"
                        text-due-at="{{ $textDueAt }}"
                        text-order-number="{{ $textOrderNumber }}"
                        text-document-title="{{ $textDocumentTitle }}"
                        text-document-subheading="{{ $textDocumentSubheading }}"
                        hide-items="{{ $hideItems }}"
                        hide-name="{{ $hideName }}"
                        hide-description="{{ $hideDescription }}"
                        hide-quantity="{{ $hideQuantity }}"
                        hide-price="{{ $hidePrice }}"
                        hide-amount="{{ $hideAmount }}"
                        hide-note="{{ $hideNote }}"
                        text-items="{{ $textItems }}"
                        text-quantity="{{ $textQuantity }}"
                        text-price="{{ $textPrice }}"
                        text-amount="{{ $textAmount }}"
                    />
                    @break
                @case('modern')
                    <x-documents.template.modern
                        type="{{ $type }}"
                        :document="$document"
                        document-template="{{ $documentTemplate }}"
                        logo="{{ $logo }}"
                        background-color="{{ $backgroundColor }}"
                        hide-footer="{{ $hideFooter }}"
                        hide-company-logo="{{ $hideCompanyLogo }}"
                        hide-company-details="{{ $hideCompanyDetails }}"
                        hide-company-name="{{ $hideCompanyName }}"
                        hide-company-address="{{ $hideCompanyAddress }}"
                        hide-company-tax-number="{{ $hideCompanyTaxNumber }}"
                        hide-company-phone="{{ $hideCompanyPhone }}"
                        hide-company-email="{{ $hideCompanyEmail }}"
                        hide-contact-info="{{ $hideContactInfo }}"
                        hide-contact-name="{{ $hideContactName }}"
                        hide-contact-address="{{ $hideContactAddress }}"
                        hide-contact-tax-number="{{ $hideContactTaxNumber }}"
                        hide-contact-phone="{{ $hideContactPhone }}"
                        hide-contact-email="{{ $hideContactEmail }}"
                        hide-order-number="{{ $hideOrderNumber }}"
                        hide-document-number="{{ $hideDocumentNumber }}"
                        hide-issued-at="{{ $hideIssuedAt }}"
                        hide-due-at="{{ $hideDueAt }}"
                        text-contact-info="{{ $textContactInfo }}"
                        text-issued-at="{{ $textIssuedAt }}"
                        text-document-number="{{ $textDocumentNumber }}"
                        text-due-at="{{ $textDueAt }}"
                        text-order-number="{{ $textOrderNumber }}"
                        text-document-title="{{ $textDocumentTitle }}"
                        text-document-subheading="{{ $textDocumentSubheading }}"
                        hide-items="{{ $hideItems }}"
                        hide-name="{{ $hideName }}"
                        hide-description="{{ $hideDescription }}"
                        hide-quantity="{{ $hideQuantity }}"
                        hide-price="{{ $hidePrice }}"
                        hide-amount="{{ $hideAmount }}"
                        hide-note="{{ $hideNote }}"
                        text-items="{{ $textItems }}"
                        text-quantity="{{ $textQuantity }}"
                        text-price="{{ $textPrice }}"
                        text-amount="{{ $textAmount }}"
                    />
                    @break
                @default
                    <x-documents.template.ddefault
                        type="{{ $type }}"
                        :document="$document"
                        document-template="{{ $documentTemplate }}"
                        logo="{{ $logo }}"
                        background-color="{{ $backgroundColor }}"
                        hide-footer="{{ $hideFooter }}"
                        hide-company-logo="{{ $hideCompanyLogo }}"
                        hide-company-details="{{ $hideCompanyDetails }}"
                        hide-company-name="{{ $hideCompanyName }}"
                        hide-company-address="{{ $hideCompanyAddress }}"
                        hide-company-tax-number="{{ $hideCompanyTaxNumber }}"
                        hide-company-phone="{{ $hideCompanyPhone }}"
                        hide-company-email="{{ $hideCompanyEmail }}"
                        hide-contact-info="{{ $hideContactInfo }}"
                        hide-contact-name="{{ $hideContactName }}"
                        hide-contact-address="{{ $hideContactAddress }}"
                        hide-contact-tax-number="{{ $hideContactTaxNumber }}"
                        hide-contact-phone="{{ $hideContactPhone }}"
                        hide-contact-email="{{ $hideContactEmail }}"
                        hide-order-number="{{ $hideOrderNumber }}"
                        hide-document-number="{{ $hideDocumentNumber }}"
                        hide-issued-at="{{ $hideIssuedAt }}"
                        hide-due-at="{{ $hideDueAt }}"
                        text-contact-info="{{ $textContactInfo }}"
                        text-issued-at="{{ $textIssuedAt }}"
                        text-document-number="{{ $textDocumentNumber }}"
                        text-due-at="{{ $textDueAt }}"
                        text-order-number="{{ $textOrderNumber }}"
                        text-document-title="{{ $textDocumentTitle }}"
                        text-document-subheading="{{ $textDocumentSubheading }}"
                        hide-items="{{ $hideItems }}"
                        hide-name="{{ $hideName }}"
                        hide-description="{{ $hideDescription }}"
                        hide-quantity="{{ $hideQuantity }}"
                        hide-discount="{{ $hideDiscount }}"
                        hide-price="{{ $hidePrice }}"
                        hide-amount="{{ $hideAmount }}"
                        hide-note="{{ $hideNote }}"
                        text-items="{{ $textItems }}"
                        text-quantity="{{ $textQuantity }}"
                        text-price="{{ $textPrice }}"
                        text-amount="{{ $textAmount }}"
                    />
            @endswitch
        @else
            @include($documentTemplate)
        @endif
    </div>
</div>
